
---
apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
  namespace: jenkins  
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
